/**
 * Unified Data Model (UDM) field paths offered as completions after `$event.`.
 *
 * Generated from the field paths used by the ~900 rules in the public
 * chronicle/detection-rules repository, plus commonly used UDM fields.
 * It's a curated subset of the full UDM schema, not the whole thing:
 * https://cloud.google.com/chronicle/docs/reference/udm-field-list
 */

/** UDM noun families; each accepts every entry of NOUN_FIELDS. */
export const UDM_NOUNS = ['principal', 'target', 'src', 'observer', 'intermediary', 'about'];

/** Field paths valid under any noun, e.g. `principal.<field>`. */
export const NOUN_FIELDS = [
  'administrative_domain',
  'application',
  'artifact',
  'artifact.ip',
  'asset',
  'asset.asset_id',
  'asset.hostname',
  'asset.ip',
  'asset.mac',
  'asset.product_object_id',
  'asset.software',
  'asset.software.description',
  'asset_id',
  'cloud',
  'cloud.environment',
  'cloud.project',
  'cloud.project.name',
  'domain',
  'domain.name',
  'email',
  'file',
  'file.file_type',
  'file.full_path',
  'file.md5',
  'file.mime_type',
  'file.names',
  'file.sha1',
  'file.sha256',
  'file.size',
  'file.tags',
  'group',
  'group.email_addresses',
  'group.group_display_name',
  'group.product_object_id',
  'hostname',
  'ip',
  'ip_geo_artifact',
  'ip_geo_artifact.location',
  'ip_geo_artifact.location.country_or_region',
  'ip_geo_artifact.location.state',
  'ip_geo_artifact.network',
  'ip_geo_artifact.network.asn',
  'ip_geo_artifact.network.carrier_name',
  'ip_geo_artifact.network.dns_domain',
  'ip_geo_artifact.network.organization_name',
  'labels',
  'labels.value',
  'location',
  'location.city',
  'location.country_or_region',
  'location.name',
  'location.region_coordinates',
  'location.region_coordinates.latitude',
  'location.region_coordinates.longitude',
  'location.state',
  'mac',
  'namespace',
  'nat_ip',
  'nat_port',
  'network',
  'network.email',
  'network.email.from',
  'platform',
  'platform_version',
  'port',
  'process',
  'process.access_mask',
  'process.command_line',
  'process.file',
  'process.file.file_metadata',
  'process.file.file_metadata.pe',
  'process.file.file_metadata.pe.import_hash',
  'process.file.full_path',
  'process.file.md5',
  'process.file.names',
  'process.file.pe_file',
  'process.file.pe_file.imphash',
  'process.file.sha1',
  'process.file.sha256',
  'process.file.size',
  'process.parent_process',
  'process.parent_process.command_line',
  'process.parent_process.file',
  'process.parent_process.file.full_path',
  'process.parent_process.file.sha256',
  'process.parent_process.pid',
  'process.parent_process.product_specific_process_id',
  'process.pid',
  'process.product_specific_process_id',
  'registry',
  'registry.registry_key',
  'registry.registry_value_data',
  'registry.registry_value_name',
  'resource',
  'resource.attribute',
  'resource.attribute.cloud',
  'resource.attribute.cloud.project',
  'resource.attribute.cloud.project.name',
  'resource.attribute.labels',
  'resource.attribute.labels.key',
  'resource.attribute.labels.value',
  'resource.attribute.roles',
  'resource.attribute.roles.name',
  'resource.name',
  'resource.product_object_id',
  'resource.resource_subtype',
  'resource.resource_type',
  'resource.type',
  'resource_ancestors',
  'resource_ancestors.attribute',
  'resource_ancestors.attribute.labels',
  'resource_ancestors.product_object_id',
  'url',
  'user',
  'user.attribute',
  'user.attribute.labels',
  'user.attribute.roles',
  'user.company_name',
  'user.department',
  'user.email_addresses',
  'user.employee_id',
  'user.first_name',
  'user.group_identifiers',
  'user.last_name',
  'user.managers',
  'user.managers.email_addresses',
  'user.product_object_id',
  'user.termination_date',
  'user.termination_date.seconds',
  'user.title',
  'user.user_display_name',
  'user.userid',
  'user.windows_sid',
];

/** Top-level field paths outside the noun families. */
export const OTHER_FIELDS = [
  'additional',
  'additional.fields',
  'extensions',
  'extensions.auth',
  'extensions.auth.auth_details',
  'extensions.auth.mechanism',
  'extensions.auth.type',
  'extracted',
  'extracted.fields',
  'metadata',
  'metadata.base_labels',
  'metadata.base_labels.log_types',
  'metadata.base_labels.namespaces',
  'metadata.collected_timestamp',
  'metadata.collected_timestamp.seconds',
  'metadata.description',
  'metadata.entity_type',
  'metadata.event_timestamp',
  'metadata.event_timestamp.seconds',
  'metadata.event_type',
  'metadata.id',
  'metadata.ingested_timestamp',
  'metadata.ingested_timestamp.seconds',
  'metadata.log_type',
  'metadata.product_event_type',
  'metadata.product_log_id',
  'metadata.product_name',
  'metadata.source_type',
  'metadata.threat',
  'metadata.threat.category_details',
  'metadata.vendor_name',
  'network',
  'network.application_protocol',
  'network.direction',
  'network.dns',
  'network.dns.answers',
  'network.dns.answers.data',
  'network.dns.questions',
  'network.dns.questions.name',
  'network.dns.questions.type',
  'network.dns.response_code',
  'network.email',
  'network.email.from',
  'network.email.mail_id',
  'network.email.subject',
  'network.email.to',
  'network.http',
  'network.http.method',
  'network.http.parsed_user_agent',
  'network.http.parsed_user_agent.browser',
  'network.http.parsed_user_agent.os',
  'network.http.referral_url',
  'network.http.response_code',
  'network.http.user_agent',
  'network.ip_protocol',
  'network.parent_session_id',
  'network.received_bytes',
  'network.sent_bytes',
  'network.session_id',
  'network.tls',
  'network.tls.client',
  'network.tls.client.ja3',
  'network.tls.server',
  'network.tls.server.certificate',
  'network.tls.server.certificate.subject',
  'security_result',
  'security_result.about',
  'security_result.about.labels',
  'security_result.action',
  'security_result.action_details',
  'security_result.category',
  'security_result.category_details',
  'security_result.description',
  'security_result.detection_fields',
  'security_result.detection_fields.value',
  'security_result.rule_id',
  'security_result.rule_name',
  'security_result.severity',
  'security_result.severity_details',
  'security_result.summary',
  'security_result.threat_name',
];

/** Entity graph (`$g.graph.entity.*`) field prefixes. */
export const GRAPH_FIELDS = [
  'graph.metadata.entity_type',
  'graph.metadata.source_type',
  'graph.metadata.product_name',
  'graph.metadata.vendor_name',
  'graph.entity.hostname',
  'graph.entity.ip',
  'graph.entity.user.userid',
  'graph.entity.user.email_addresses',
  'graph.entity.file.sha256',
  'graph.entity.domain.name',
  'graph.entity.asset.hostname',
  'graph.relations.entity.hostname',
];

let cache: string[] | undefined;

/** Every known field path, sorted. */
export function allUdmFields(): string[] {
  if (!cache) {
    const set = new Set<string>([...OTHER_FIELDS, ...GRAPH_FIELDS]);
    for (const noun of UDM_NOUNS) {
      set.add(noun);
      for (const f of NOUN_FIELDS) set.add(`${noun}.${f}`);
    }
    cache = [...set].sort();
  }
  return cache;
}
