/**
 * MITRE framework support: ATT&CK Enterprise, ICS and Mobile, and ATLAS
 * (adversarial threats to AI systems).
 *
 * Data is generated by `npm run update-mitre` from MITRE's official releases
 * into catalog/mitre-data.json. IDs are unique across the four frameworks,
 * but tactic names are not ("Initial Access" exists in all of them).
 */

import data from './catalog/mitre-data.json';

export type MitreFramework = 'enterprise' | 'ics' | 'mobile' | 'atlas';
export const MITRE_FRAMEWORKS: MitreFramework[] = ['enterprise', 'ics', 'mobile', 'atlas'];

interface TechniqueData {
  n: string;
  t: string[];
  d?: number;
  r?: string | true;
}

interface FrameworkData {
  name: string;
  domain: string;
  url: string;
  version: string;
  tactics: Record<string, string>;
  techniques: Record<string, TechniqueData>;
}

const FRAMEWORKS = (data as unknown as { frameworks: Record<MitreFramework, FrameworkData> }).frameworks;
export const MITRE_DATA_DATE = (data as { generated: string }).generated;

export interface MitreConfig {
  /** Frameworks whose IDs are accepted. */
  frameworks: MitreFramework[];
  /** Framework used to resolve ambiguous tactic names when a rule has no other MITRE IDs. */
  defaultFramework: MitreFramework;
  /** Meta key holding tactic IDs. */
  tacticKey: string;
  /** Meta key holding technique IDs. */
  techniqueKey: string;
}

export const DEFAULT_MITRE_CONFIG: MitreConfig = {
  frameworks: [...MITRE_FRAMEWORKS],
  defaultFramework: 'enterprise',
  tacticKey: 'tactic',
  techniqueKey: 'technique',
};

/** Alternative meta keys seen in the wild that map onto tactic/technique. */
export const ALTERNATE_MITRE_KEYS: Record<string, 'tactic' | 'technique'> = {
  mitre_attack_tactic: 'tactic',
  mitre_tactic: 'tactic',
  attack_tactic: 'tactic',
  tactics: 'tactic',
  mitre_attack_technique: 'technique',
  mitre_attack_technique_id: 'technique',
  mitre_technique: 'technique',
  attack_technique: 'technique',
  techniques: 'technique',
};

export interface MitreTactic {
  kind: 'tactic';
  framework: MitreFramework;
  id: string;
  name: string;
}

export interface MitreTechnique {
  kind: 'technique';
  framework: MitreFramework;
  id: string;
  name: string;
  tactics: string[];
  deprecated: boolean;
  /** Replacement technique ID when revoked (true when revoked without a known replacement). */
  revokedBy?: string | true;
}

export type MitreEntry = MitreTactic | MitreTechnique;

const TACTIC_ID = /^(?:TA\d{4}|AML\.TA\d{4})$/;
const TECHNIQUE_ID = /^(?:T\d{4}(?:\.\d{3})?|AML\.T\d{4}(?:\.\d{3})?)$/;
export function isTacticId(id: string): boolean {
  return TACTIC_ID.test(id);
}

export function isTechniqueId(id: string): boolean {
  return TECHNIQUE_ID.test(id);
}

export function frameworkInfo(f: MitreFramework): { name: string; domain: string; url: string; version: string } {
  const { name, domain, url, version } = FRAMEWORKS[f];
  return { name, domain, url, version };
}

export function lookupMitre(id: string, frameworks: MitreFramework[] = MITRE_FRAMEWORKS): MitreEntry | undefined {
  for (const f of frameworks) {
    const fw = FRAMEWORKS[f];
    if (fw.tactics[id]) return { kind: 'tactic', framework: f, id, name: fw.tactics[id] };
    const t = fw.techniques[id];
    if (t) {
      return { kind: 'technique', framework: f, id, name: t.n, tactics: t.t, deprecated: !!t.d, revokedBy: t.r };
    }
  }
  return undefined;
}

/** All tactics / techniques of the given frameworks (for completion). */
export function allMitre(kind: 'tactic' | 'technique', frameworks: MitreFramework[] = MITRE_FRAMEWORKS): MitreEntry[] {
  const out: MitreEntry[] = [];
  for (const f of frameworks) {
    const fw = FRAMEWORKS[f];
    if (kind === 'tactic') {
      for (const [id, name] of Object.entries(fw.tactics)) out.push({ kind: 'tactic', framework: f, id, name });
    } else {
      for (const [id, t] of Object.entries(fw.techniques)) {
        if (t.r) continue;
        out.push({ kind: 'technique', framework: f, id, name: t.n, tactics: t.t, deprecated: !!t.d });
      }
    }
  }
  return out;
}

/** Finds tactics/techniques whose name matches (case-insensitive). */
export function findByName(name: string, kind: 'tactic' | 'technique', frameworks: MitreFramework[] = MITRE_FRAMEWORKS): MitreEntry[] {
  const needle = name.trim().toLowerCase();
  return allMitre(kind, frameworks).filter((e) => e.name.toLowerCase() === needle && !(e.kind === 'technique' && e.deprecated));
}

export function mitreUrl(e: MitreEntry): string {
  if (e.framework === 'atlas') return `https://atlas.mitre.org/${e.kind === 'tactic' ? 'tactics' : 'techniques'}/${e.id}`;
  if (e.kind === 'tactic') return `https://attack.mitre.org/tactics/${e.id}/`;
  return `https://attack.mitre.org/techniques/${e.id.replace('.', '/')}/`;
}

export function mitreMarkdown(e: MitreEntry): string {
  const fw = frameworkInfo(e.framework);
  const lines = [`**${e.id}** — ${e.name}`, '', `${fw.name} ${e.kind} · v${fw.version}`];
  if (e.kind === 'technique') {
    if (e.revokedBy) lines.push('', `⚠️ Revoked${typeof e.revokedBy === 'string' ? `: use **${e.revokedBy}**` : ''}.`);
    else if (e.deprecated) lines.push('', '⚠️ Deprecated.');
    if (e.tactics.length) {
      lines.push('', 'Tactics: ' + e.tactics.map((t) => `${t} ${FRAMEWORKS[e.framework].tactics[t] ?? ''}`.trim()).join(', '));
    }
  }
  lines.push('', `[${mitreUrl(e)}](${mitreUrl(e)})`);
  return lines.join('\n');
}

export interface IdSpan {
  text: string;
  /** Offset within the meta value string. */
  start: number;
  end: number;
}

/**
 * Splits a meta value into items on commas/semicolons/pipes. Items are either
 * IDs ("T1110") or free text ("Credential Access"). "T1110 - Brute Force"
 * style items are reduced to their ID.
 */
export function splitMitreValue(value: string): IdSpan[] {
  const out: IdSpan[] = [];
  const re = /[^,;|]+/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(value))) {
    const raw = m[0];
    const lead = raw.length - raw.trimStart().length;
    const text = raw.trim();
    if (!text) continue;
    const idMatch = /^((?:AML\.)?TA?\d{4}(?:\.\d{3})?)\b/.exec(text);
    const item = idMatch ? idMatch[1] : text;
    out.push({ text: item, start: m.index + lead, end: m.index + lead + item.length });
  }
  return out;
}

export function frameworkOfId(id: string): MitreFramework | undefined {
  return lookupMitre(id)?.framework;
}
